{"cells":[{"cell_type":"markdown","metadata":{"id":"aGveL5iFhIXV"},"source":["# Google Colab Setup\n","**Only for users on Google Colab**"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"3uDE-1LZhKLe"},"outputs":[],"source":["# Define functions to connect to Google and change directories\n","def connectDrive():\n","    from google.colab import drive\n","    drive.mount('/content/drive', force_remount=True)\n","\n","def changeDirectory(path):\n","    import os\n","    original_path = os.getcwd()\n","    os.chdir(path)\n","    new_path = os.getcwd()\n","    print(\"Original path: \",original_path)\n","    print(\"New path: \",new_path)\n","\n","# Connect to Google Drive\n","connectDrive()\n","\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"T4Dl7mvw6ZdW"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-39-c02de16eadcf\u003e\", line 2, in \u003ccell line: 2\u003e\n","    changeDirectory(\"/content/drive/MyDrive/數位課程_檔案/Data Mining\")\n","  File \"\u003cipython-input-38-26a3eb2be8c2\u003e\", line 8, in changeDirectory\n","    original_path = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-39-c02de16eadcf\u003e\", line 2, in \u003ccell line: 2\u003e\n","    changeDirectory(\"/content/drive/MyDrive/數位課程_檔案/Data Mining\")\n","  File \"\u003cipython-input-38-26a3eb2be8c2\u003e\", line 8, in changeDirectory\n","    original_path = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-39-c02de16eadcf\u003e\", line 2, in \u003ccell line: 2\u003e\n","    changeDirectory(\"/content/drive/MyDrive/數位課程_檔案/Data Mining\")\n","  File \"\u003cipython-input-38-26a3eb2be8c2\u003e\", line 8, in changeDirectory\n","    original_path = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Change path\n","changeDirectory(\"/content/drive/MyDrive/數位課程_檔案/Data Mining\")"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"kB9kYs1K6T-v"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-39-d3dc51b95a25\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('pwd', '')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-84\u003e\", line 2, in pwd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 295, in pwd\n","    return os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-39-d3dc51b95a25\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('pwd', '')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-84\u003e\", line 2, in pwd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 295, in pwd\n","    return os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-39-d3dc51b95a25\u003e\", line 1, in \u003ccell line: 1\u003e\n","    get_ipython().run_line_magic('pwd', '')\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2418, in run_line_magic\n","    result = fn(*args, **kwargs)\n","  File \"\u003cdecorator-gen-84\u003e\", line 2, in pwd\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magic.py\", line 187, in \u003clambda\u003e\n","    call = lambda f, *a, **k: f(*a, **k)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/magics/osm.py\", line 295, in pwd\n","    return os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["pwd"]},{"cell_type":"markdown","metadata":{"id":"xTebGltzhEvK"},"source":["# Import Libraries"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"la9xwrbf-il-"},"outputs":[],"source":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"YTkxCjPF6BA-"},"outputs":[],"source":["pip install dask"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"IRk4NbKQhEvK","scrolled":true},"outputs":[],"source":["'''Main'''\n","import numpy as np\n","import pandas as pd\n","import os, time, re\n","import pickle, gzip\n","\n","'''Data Viz'''\n","import matplotlib.pyplot as plt\n","import seaborn as sns\n","color = sns.color_palette()\n","import matplotlib as mpl\n","\n","%matplotlib inline\n","\n","'''Data Prep and Model Evaluation'''\n","from sklearn import preprocessing as pp\n","from sklearn.model_selection import train_test_split\n","from sklearn.model_selection import StratifiedKFold\n","from sklearn.metrics import log_loss\n","from sklearn.metrics import precision_recall_curve, average_precision_score\n","from sklearn.metrics import roc_curve, auc, roc_auc_score\n","\n","'''Algos'''\n","import lightgbm as lgb\n","\n","'''TensorFlow and Keras'''\n","import tensorflow as tf\n","from tensorflow import keras\n","K = keras.backend\n","\n","from tensorflow.keras.models import Sequential, Model\n","from tensorflow.keras.layers import Activation, Dense, Dropout\n","from tensorflow.keras.layers import BatchNormalization, Input, Lambda\n","from tensorflow.keras import regularizers\n","from tensorflow.keras.losses import mse, binary_crossentropy"]},{"cell_type":"markdown","metadata":{"id":"z0PBXaIlhEvL"},"source":["## Check library versions \u0026 set seed"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"c0RmBYsuhEvL"},"outputs":[],"source":["import sys, sklearn\n","print(f'sklearn    {sklearn.__version__}')\n","print(f'tensorflow {tf.__version__}')\n","print(f'keras      {keras.__version__}')\n","print(f'numpy      {np.__version__}')\n","print(f'lightgbp   {lgb.__version__}')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FJ-C29DkhEvM"},"outputs":[],"source":["# To make the output stable across runs\n","tf.random.set_seed(42)\n","np.random.seed(42)"]},{"cell_type":"markdown","metadata":{"id":"dYhp9rmehEvM"},"source":["# Data Preparation"]},{"cell_type":"markdown","metadata":{"id":"alvX1KDrhEvM"},"source":["## Load the data"]},{"cell_type":"code","execution_count":null,"metadata":{"colab":{"background_save":true},"id":"UVliLoKhhEvM"},"outputs":[{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n","ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-43-d1903e49c093\u003e\", line 2, in \u003ccell line: 2\u003e\n","    current_path = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-43-d1903e49c093\u003e\", line 2, in \u003ccell line: 2\u003e\n","    current_path = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]},{"name":"stderr","output_type":"stream","text":["ERROR:root:Internal Python error in the inspect module.\n","Below is the traceback from this internal error.\n","\n"]},{"name":"stdout","output_type":"stream","text":["Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3553, in run_code\n","    exec(code_obj, self.user_global_ns, self.user_ns)\n","  File \"\u003cipython-input-43-d1903e49c093\u003e\", line 2, in \u003ccell line: 2\u003e\n","    current_path = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'OSError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3473, in run_ast_nodes\n","    if (await self.run_code(code, result,  async_=asy)):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3575, in run_code\n","    self.showtraceback(running_compiled_code=True)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1124, in structured_traceback\n","    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3030, in _run_cell\n","    return runner(coro)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py\", line 78, in _pseudo_sync_runner\n","    coro.send(None)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3257, in run_cell_async\n","    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 3492, in run_ast_nodes\n","    self.showtraceback()\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2101, in showtraceback\n","    stb = self.InteractiveTB.structured_traceback(etype,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1367, in structured_traceback\n","    return FormattedTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1267, in structured_traceback\n","    return VerboseTB.structured_traceback(\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1142, in structured_traceback\n","    formatted_exceptions += self.format_exception_as_a_whole(etype, evalue, etb, lines_of_context,\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1082, in format_exception_as_a_whole\n","    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 382, in find_recursion\n","    return len(records), 0\n","TypeError: object of type 'NoneType' has no len()\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py\", line 2099, in showtraceback\n","    stb = value._render_traceback_()\n","AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 1101, in get_records\n","    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 248, in wrapped\n","    return f(*args, **kwargs)\n","  File \"/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py\", line 281, in _fixed_getinnerframes\n","    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))\n","  File \"/usr/lib/python3.10/inspect.py\", line 1662, in getinnerframes\n","    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)\n","  File \"/usr/lib/python3.10/inspect.py\", line 1620, in getframeinfo\n","    filename = getsourcefile(frame) or getfile(frame)\n","  File \"/usr/lib/python3.10/inspect.py\", line 829, in getsourcefile\n","    module = getmodule(object, filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 861, in getmodule\n","    file = getabsfile(object, _filename)\n","  File \"/usr/lib/python3.10/inspect.py\", line 845, in getabsfile\n","    return os.path.normcase(os.path.abspath(_filename))\n","  File \"/usr/lib/python3.10/posixpath.py\", line 384, in abspath\n","    cwd = os.getcwd()\n","OSError: [Errno 107] Transport endpoint is not connected\n"]}],"source":["# Load the data\n","current_path = os.getcwd()\n","file = os.path.sep.join(['/', 'datasets', 'credit_card_data', 'credit_card.csv'])\n","data = pd.read_csv(current_path + file)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"BSJx40_ihEvN"},"outputs":[],"source":["# Create X matrix\n","dataX = data.copy().drop(['Class','Time'],axis=1)\n","\n","# Create y Matrix\n","dataY = data['Class'].copy()"]},{"cell_type":"markdown","metadata":{"id":"Vh8-COaRhEvN"},"source":["## Split into train and test"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"7JL2LmEjhEvN"},"outputs":[],"source":["# Split into train and test\n","X_train, X_test, y_train, y_test = train_test_split(\n","                                    dataX, dataY, test_size=0.33,\n","                                    random_state=2024, stratify=dataY)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"IlX_4NxihEvO"},"outputs":[],"source":["# Shape of data\n","print([x.shape for x in (X_train, X_test, y_train, y_test)])"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"PQBBAclEhEvP"},"outputs":[],"source":["# Number of negative and positive examples\n","#X_train=190820 (y=0 and y=1)\n","#X_train=190490 (y=0)\n","#X_train=330 (y=1)\n","np.sum(y_train==0),np.sum(y_train==1)"]},{"cell_type":"markdown","metadata":{"id":"0eWg5qLWhEvP"},"source":["## Scale the data"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"sppJlcYXhEvQ"},"outputs":[],"source":["# Suppress warnings\n","pd.set_option('mode.chained_assignment', None)\n","\n","# Scale data\n","featuresToScale = dataX.columns\n","sX = pp.StandardScaler(copy=True, with_mean=True, with_std=True)\n","X_train.loc[:,featuresToScale] = sX.fit_transform(X_train.loc[:,featuresToScale])\n","X_test.loc[:,featuresToScale] = sX.transform(X_test.loc[:,featuresToScale])"]},{"cell_type":"markdown","metadata":{"id":"BJ5_vhx2hEvQ"},"source":["## Drop 90% of the labels(==1) from the training set"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"iCVLgISrhEvQ"},"outputs":[],"source":["# Drop 90% of the labels from the training set\n","# 330- 297( drop 90%)= 33\n","# all X_train=190820 (y=0 and y=1) - 297 = 190523\n","toDrop = y_train[y_train==1].sample(frac=0.90,random_state=2024)\n","X_train.drop(labels=toDrop.index,inplace=True)\n","y_train.drop(labels=toDrop.index,inplace=True)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"4qJzD1Ye5n3E"},"outputs":[],"source":["len(X_train)"]},{"cell_type":"markdown","metadata":{"id":"xSVDgTLvhEvR"},"source":["## Check the number of fraudulent cases left after dropping 90% of the cases"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"WD7epvmqhEvR"},"outputs":[],"source":["# Check the number of fruadulant cases left after dropping 90%\n","np.sum(y_train==0),np.sum(y_train==1)"]},{"cell_type":"markdown","metadata":{"id":"WHchmzZXhEvS"},"source":["## Define evaluation function and plotting function"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rBuqdb9ChEvS"},"outputs":[],"source":["# Calculate reconstruction error\n","def anomalyScores(originalDF, reducedDF):\n","    loss = np.sum((np.array(originalDF) -\n","                   np.array(reducedDF))**2, axis=1)\n","    loss = pd.Series(data=loss,index=originalDF.index)\n","    loss = (loss-np.min(loss))/(np.max(loss)-np.min(loss))\n","    return loss"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"fQGFvGWmhEvS"},"outputs":[],"source":["# Plot results\n","def plotResults(trueLabels, anomalyScores, returnPreds = False):\n","    preds = pd.concat([trueLabels, anomalyScores], axis=1)\n","    preds.columns = ['trueLabel', 'anomalyScore']\n","    precision, recall, thresholds = \\\n","        precision_recall_curve(preds['trueLabel'],\n","                               preds['anomalyScore'])\n","    average_precision = average_precision_score(\n","                        preds['trueLabel'], preds['anomalyScore'])\n","\n","    plt.step(recall, precision, color='k', alpha=0.7, where='post')\n","    plt.fill_between(recall, precision, step='post', alpha=0.3, color='k')\n","\n","    plt.xlabel('Recall')\n","    plt.ylabel('Precision')\n","    plt.ylim([0.0, 1.05])\n","    plt.xlim([0.0, 1.0])\n","\n","    plt.title('Precision-Recall curve: Average Precision = \\\n","        {0:0.2f}'.format(average_precision))\n","\n","    fpr, tpr, thresholds = roc_curve(preds['trueLabel'],\n","                                     preds['anomalyScore'])\n","    areaUnderROC = auc(fpr, tpr)\n","\n","    plt.figure()\n","    plt.plot(fpr, tpr, color='r', lw=2, label='ROC curve')\n","    plt.plot([0, 1], [0, 1], color='k', lw=2, linestyle='--')\n","    plt.xlim([0.0, 1.0])\n","    plt.ylim([0.0, 1.05])\n","    plt.xlabel('False Positive Rate')\n","    plt.ylabel('True Positive Rate')\n","    plt.title('Receiver operating characteristic: Area under the \\\n","        curve = {0:0.2f}'.format(areaUnderROC))\n","    plt.legend(loc=\"lower right\")\n","    plt.show()\n","\n","    if returnPreds==True:\n","        return preds, average_precision"]},{"cell_type":"markdown","metadata":{"id":"zC-YE7MLhEvS"},"source":["## Define a new function to assess precision at a given recall threshold"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"dITIXmVfhEvT"},"outputs":[],"source":["# Define new function to assess precision at a given recall threshold\n","# 給定recall threshold, 故共要抓到threshold_value 這麼多的量\n","# i/j為precision的值\n","def precisionAnalysis(df, column, threshold):\n","    df.sort_values(by=column, ascending=False, inplace=True)\n","    threshold_value = threshold*df.trueLabel.sum()\n","    i = 0\n","    j = 0\n","    while i \u003c threshold_value+1:\n","        if df.iloc[j][\"trueLabel\"]==1:\n","            i += 1 #真的有病\n","        j += 1\n","    return df, i/j"]},{"cell_type":"markdown","metadata":{"id":"hYH_w5JkhEvT"},"source":["# Supervised Model"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"cPJQQgpYhEvT"},"outputs":[],"source":["# Create 5 k-fold sets\n","k_fold = StratifiedKFold(n_splits=5,shuffle=True,random_state=2024)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"b73bOEINhEvT"},"outputs":[],"source":["# LightGBM parameters\n","params_lightGB = {\n","    'task': 'train',\n","    'num_class':1,\n","    'boosting': 'gbdt',\n","    'objective': 'binary',\n","    'metric': 'binary_logloss',\n","    'metric_freq':50,\n","    'is_training_metric':False,\n","    'max_depth':4,\n","    'num_leaves': 31,\n","    'learning_rate': 0.01,\n","    'feature_fraction': 1.0,\n","    'bagging_fraction': 1.0,\n","    'bagging_freq': 0,\n","    'bagging_seed': 2018,\n","    'verbose': -1,\n","    'num_threads':16\n","}"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"n-qVX6-6hEvU"},"outputs":[],"source":["# Train and Evaluate Model\n","trainingScores = []\n","cvScores = []\n","predictionsBasedOnKFolds = pd.DataFrame(data=[], index=y_train.index,\n","                                        columns=['prediction'])\n","\n","for train_index, cv_index in k_fold.split(np.zeros(len(X_train)),\n","                                          y_train.ravel()):\n","    X_train_fold, X_cv_fold = X_train.iloc[train_index,:], X_train.iloc[cv_index,:]\n","    y_train_fold, y_cv_fold = y_train.iloc[train_index],   y_train.iloc[cv_index]\n","\n","    lgb_train = lgb.Dataset(X_train_fold, y_train_fold)\n","    lgb_eval = lgb.Dataset(X_cv_fold, y_cv_fold, reference=lgb_train)\n","    gbm = lgb.train(params_lightGB, lgb_train, num_boost_round=2000,\n","                   valid_sets=lgb_eval)# ,early_stopping_rounds=200)\n","\n","    loglossTraining = log_loss(y_train_fold, gbm.predict(X_train_fold,\n","                                num_iteration=gbm.best_iteration))\n","    trainingScores.append(loglossTraining)\n","\n","    predictionsBasedOnKFolds.loc[X_cv_fold.index,'prediction'] = gbm.predict(\n","        X_cv_fold, num_iteration=gbm.best_iteration)\n","    loglossCV = log_loss(y_cv_fold, predictionsBasedOnKFolds.loc[X_cv_fold.index,'prediction'])\n","    cvScores.append(loglossCV)\n","\n","    print(f'Training Log Loss: {loglossTraining}')\n","    print(f'CV Log Loss: {loglossCV}')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"qLlXetXyhEvU"},"outputs":[],"source":["# Print results\n","loglossLightGBMGradientBoosting = log_loss(y_train,\n","        predictionsBasedOnKFolds.loc[:,'prediction'])\n","print(f'LightGBM Gradient Boosting Log Loss: {round(loglossLightGBMGradientBoosting,4)}')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"45SN97pRhEvV"},"outputs":[],"source":["# Plot results\n","preds, average_precision = plotResults(y_train,\n","                        predictionsBasedOnKFolds.loc[:,'prediction'], True)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"GRvfl2AHhEvV"},"outputs":[],"source":["# Evaluate on Test Set\n","predictions = pd.Series(data=gbm.predict(X_test,\n","                num_iteration=gbm.best_iteration), index=X_test.index)\n","preds, average_precision = plotResults(y_test, predictions, True)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"wa2uxDNihEvV"},"outputs":[],"source":["# Calculate precision at 75% recall\n","preds, precision = precisionAnalysis(preds, \"anomalyScore\", 0.75)\n","print(f'Precision at 75% recall is {round(precision,4)}')"]},{"cell_type":"markdown","metadata":{"id":"v3ETpMMthEvW"},"source":["# Unsupervised Model"]},{"cell_type":"markdown","metadata":{"id":"N2GzwupnhEvW"},"source":["## Oversample"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"f7GSuPCJhEva"},"outputs":[],"source":["# Take the 33 fraudulent cases, duplicate these 100 times and then append them to the training set\n","\n","#X[y_train==1]==\u003e X[True, False, True, True, False,True,..] ==\u003e\n","# X[0],X[2],X[3],[5],...\n","# [X[0],X[2],X[3],[5],...]*2 ==\u003e [X[0],X[2],X[3],[5],...,X[0],X[2],X[3],[5],...]\n","oversample_multiplier = 100\n","## X_train_original=190523 + 33*100 =193823\n","X_train_original = X_train.copy()\n","y_train_original = y_train.copy()\n","X_test_original = X_test.copy()\n","y_test_original = y_test.copy()\n","X_train_oversampled = X_train.copy()\n","y_train_oversampled = y_train.copy()\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"OYnaMKCn5n3G"},"outputs":[],"source":["print([x.shape for x in (X_train, X_test, y_train, y_test)])"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"3bF6dsXy5n3K"},"outputs":[],"source":["print(X_train_oversampled.shape)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"8VEkw7I45n3K"},"outputs":[],"source":["#X_train_oversampled(190523, 29) append([(33,29)]*100)\n","X_train_oversampled = X_train_oversampled.append( \\\n","        [X_train_oversampled[y_train==1]]*oversample_multiplier, \\\n","        ignore_index=False)\n","y_train_oversampled = y_train_oversampled.append( \\\n","        [y_train_oversampled[y_train==1]]*oversample_multiplier, \\\n","        ignore_index=False)\n","\n"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"m-nDmbqZ5n3K"},"outputs":[],"source":["X_train = X_train_oversampled.copy()\n","y_train = y_train_oversampled.copy()"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"1axEy087hEva"},"outputs":[],"source":["# View shape\n","X_train.shape, y_train.shape"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"bhsaZ_iI5n3L"},"outputs":[],"source":["np.sum(y_train==1) # 33+33*100=3333"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"vijbtCq35n3L"},"outputs":[],"source":["y_train[-3301:]"]},{"cell_type":"markdown","metadata":{"id":"hbYqQQFGhEvb"},"source":["## Design \u0026 Train Sparse Autoencoder\n","\n","### 29 \u003e 40 \u003e29"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"wSna7pXyhEvc"},"outputs":[],"source":["# A sparse two-layer overcomplete autoencoder with a linear a linear activation function.\n","# Forty nodes in the hidden layer and a dropout of 2%\n","\n","model = Sequential()\n","model.add(Dense(units=40, activation='linear', \\\n","                activity_regularizer=regularizers.l1(10e-5), \\\n","                input_dim=29,name='hidden_layer'))\n","model.add(Dropout(0.02))\n","model.add(Dense(units=29, activation='linear'))"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"ClCwhOxuhEvc"},"outputs":[],"source":["# Compile model\n","model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"w-pni43B5n3L"},"outputs":[],"source":["model.summary()"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"xK_VPUMOhEvc"},"outputs":[],"source":["# Train model\n","num_epochs =  5\n","batch_size = 32\n","\n","history = model.fit(x=X_train, y=X_train, epochs=num_epochs,\n","                    batch_size=batch_size, shuffle=True,\n","                    validation_split=0.20, verbose=1)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"C9LET90zhEvc"},"outputs":[],"source":["# Evaluate model\n","predictionsTrain = model.predict(X_train_original, verbose=1)\n","anomalyScoresAETrain = anomalyScores(X_train_original, predictionsTrain)\n","preds, average_precision = plotResults(y_train_original, anomalyScoresAETrain, True)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Gnf6WN9ghEvc"},"outputs":[],"source":["# Evaluate on test set\n","predictions = model.predict(X_test, verbose=1)\n","anomalyScoresAE = anomalyScores(X_test, predictions)\n","preds, average_precision = plotResults(y_test, anomalyScoresAE, True)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"iIi8afRuhEvc"},"outputs":[],"source":["# Calculate precision at 75% recall\n","preds, precision = precisionAnalysis(preds, \"anomalyScore\", 0.75)\n","print(f'Precision at 75% recall is {round(precision,4)}')"]},{"cell_type":"markdown","metadata":{"id":"XYfywfRmhEvd"},"source":["# Semisupervised Model"]},{"cell_type":"markdown","metadata":{"id":"yWWntMWYhEvd"},"source":["## Combine Hidden Layer of Autoencoder (Learned Features) with Original Feature Set\n","\n","將來自AutoEncoder 所學到的特徵也加入到原本的訓練集, 使到訓練集的特徵有29+40=69個.\n","然後再進行LightGBM進行預測."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"8Y2ZwhzhhEvd"},"outputs":[],"source":["# Generate hidden layer from autoencoder to pass into supervised model\n","layer_name = 'hidden_layer'\n","\n","intermediate_layer_model  = Model(inputs=model.input,\n","                                  outputs=model.get_layer(layer_name).output)\n","intermediate_output_train = intermediate_layer_model.predict(X_train_original)\n","intermediate_output_test  = intermediate_layer_model.predict(X_test_original)\n","\n","intermediate_output_trainDF = pd.DataFrame(data=intermediate_output_train,\n","                                           index=X_train_original.index)\n","intermediate_output_testDF  = pd.DataFrame(data=intermediate_output_test,\n","                                           index=X_test_original.index)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"SvxCimR25n3N"},"outputs":[],"source":["intermediate_layer_model.summary()"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"X-4_GFtwhEve"},"outputs":[],"source":["# Add hidden layer dimensions to original dataset 29+40=69\n","X_train = X_train_original.merge(intermediate_output_trainDF,\n","                                 left_index=True,right_index=True)\n","X_test  = X_test_original.merge(intermediate_output_testDF,\n","                                left_index=True,right_index=True)\n","y_train = y_train_original.copy()"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"vWBf9Izi5n3N"},"outputs":[],"source":["X_train.shape"]},{"cell_type":"markdown","metadata":{"id":"kgcCRWGohEve"},"source":["## Supervised Model on Autoencoder + Original Feature Set"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"W_o0Nc8BhEve"},"outputs":[],"source":["# Train and Evaluate LightGBM Model with Original + Autoencoder Dimensions\n","trainingScores = []\n","cvScores = []\n","predictionsBasedOnKFolds = pd.DataFrame(data=[],index=y_train.index,  columns=['prediction'])\n","\n","for train_index, cv_index in k_fold.split(np.zeros(len(X_train)), y_train.ravel()):\n","    X_train_fold, X_cv_fold = X_train.iloc[train_index,:], X_train.iloc[cv_index,:]\n","    y_train_fold, y_cv_fold = y_train.iloc[train_index], y_train.iloc[cv_index]\n","\n","    lgb_train = lgb.Dataset(X_train_fold, y_train_fold)\n","    lgb_eval = lgb.Dataset(X_cv_fold, y_cv_fold, reference=lgb_train)\n","    gbm = lgb.train(params_lightGB, lgb_train, num_boost_round=5000,\n","                   valid_sets=lgb_eval, early_stopping_rounds=200)\n","\n","    loglossTraining = log_loss(y_train_fold, gbm.predict(X_train_fold,num_iteration=gbm.best_iteration))\n","    trainingScores.append(loglossTraining)\n","\n","    predictionsBasedOnKFolds.loc[X_cv_fold.index,'prediction'] = gbm.predict(X_cv_fold, num_iteration=gbm.best_iteration)\n","    loglossCV = log_loss(y_cv_fold, predictionsBasedOnKFolds.loc[X_cv_fold.index,'prediction'])\n","    cvScores.append(loglossCV)\n","\n","    print(f'Training Log Loss: {round(loglossTraining,4)}')\n","    print(f'CV Log Loss: {round(loglossCV,4)}' )"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"u0ZCqTOihEve"},"outputs":[],"source":["# Print results\n","loglossLightGBMGradientBoosting = log_loss(y_train, predictionsBasedOnKFolds.loc[:,'prediction'])\n","print(f'LightGBM Gradient Boosting Log Loss: {round(loglossLightGBMGradientBoosting,4)}')"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"nP5Q36XqhEve"},"outputs":[],"source":["# Evaluate results\n","preds, average_precision = plotResults(y_train, predictionsBasedOnKFolds.loc[:,'prediction'], True)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"NEZulO-yhEve"},"outputs":[],"source":["# Evaluate results on test set\n","predictions = pd.Series(data=gbm.predict(X_test, num_iteration=gbm.best_iteration),index=X_test.index)\n","preds, average_precision = plotResults(y_test, predictions, True)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"sknToNUvhEvf"},"outputs":[],"source":["# Calculate precision at 75% recall\n","preds, precision = precisionAnalysis(preds, \"anomalyScore\", 0.75)\n","print(f'{round(precision,4)}')"]},{"cell_type":"markdown","metadata":{"id":"XsA625tm5n3O"},"source":["# Summary\n","\n","```\n","(1)Supervised Model : PR 0.66, ,在Recall 0.75下, 對測試集的Precision Score 為 0.0612\n","(2)Sparse Autoencoder: PR 0.16 , 在Recall 0.75下, 對測試集的Precision Score 為 0.0954\n","(3)Supervised Model on Autoencoder + Original Feature Set: PR 0.68. 在Recall 0.75下, 對測試集的Precision Score 0.2124\n","\n","會隨著Radom state 值, 可能有所改變\n","\n","```"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"vo1wUtn8hEvf"},"outputs":[],"source":["# Analyze most important features\n","featuresImportance = pd.DataFrame(data=list(gbm.feature_importance()), index=X_train.columns,columns=['featImportance'])\n","featuresImportance['featImportance'] = featuresImportance/featuresImportance.sum()\n","featuresImportance.sort_values(by='featImportance', ascending=False,inplace=True)\n","featuresImportance[:20]"]},{"cell_type":"markdown","metadata":{"id":"Upm-pD7m5n3O"},"source":["排名比較前面(重要)的特徵, 大部份是來自Autoencoder的特徵"]},{"cell_type":"markdown","metadata":{"id":"987b_lN0hEvf"},"source":["# Conclusion"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"FnJG5DmRhjew"},"outputs":[],"source":["import datetime as dt\n","print(\"Completed: \", dt.datetime.now())"]}],"metadata":{"accelerator":"GPU","colab":{"gpuType":"T4","name":"","version":""},"kernelspec":{"display_name":"Python 3","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.8.5"},"toc":{"base_numbering":1,"nav_menu":{},"number_sections":false,"sideBar":true,"skip_h1_title":false,"title_cell":"Table of Contents","title_sidebar":"Contents","toc_cell":false,"toc_position":{},"toc_section_display":true,"toc_window_display":false}},"nbformat":4,"nbformat_minor":0}